//
// shit_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_SHIT_ISPC_H
#define ISPC_SHIT_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Enumerator types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_ENUM_RTCGeometryFlags__
#define __ISPC_ENUM_RTCGeometryFlags__
enum RTCGeometryFlags {
    RTC_GEOMETRY_STATIC = 0,
    RTC_GEOMETRY_DEFORMABLE = 1,
    RTC_GEOMETRY_DYNAMIC = 2 
};
#endif


#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT___RTCScene__
#define __ISPC_STRUCT___RTCScene__
struct __RTCScene {
};
#endif

#ifndef __ISPC_STRUCT_RTCRay__
#define __ISPC_STRUCT_RTCRay__
struct RTCRay {
    float orgx;
    float orgy;
    float orgz;
    float dirx;
    float diry;
    float dirz;
    float tnear;
    float tfar;
    float time;
    uint32_t mask;
    float Ngx;
    float Ngy;
    float Ngz;
    float u;
    float v;
    uint32_t geomID;
    uint32_t primID;
    uint32_t instID;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void calculateSceneColor(struct __RTCScene * scene, struct RTCRay * ray, int32_t width, int32_t height, uint8_t * gl_FragCoord);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_SHIT_ISPC_H
